package kho

import (
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/tamnd/gao/luat"
	"github.com/tamnd/gao/may"
)

// The dataset card, generated rather than written.
//
// A card written by hand describes the release before last. It says 40 billion
// tokens because that was true in March, it lists four sources because a fifth
// was added after somebody last opened the file, and there is no way to tell by
// looking at it which of its numbers have gone stale. Every number here comes
// out of the manifest that sealed the snapshot, so a card that disagrees with
// the data is a bug rather than an oversight, and regenerating it is the same
// command every time rather than an afternoon.
//
// The parts a person actually needs are the ones a generated card is good at:
// what is in the repo, what is not in it and why, how many documents and tokens
// there are, which stages produced them at which versions, and the one line that
// reads the thing without downloading it. The parts a generated card is bad at,
// the argument for why the corpus is built this way, live in the repository and
// are linked rather than restated.

// CardName is the file a dataset card lives in on the Hub.
const CardName = "README.md"

// Repository is where the card sends a reader who wants the argument rather
// than the numbers.
const Repository = "https://github.com/tamnd/gao"

// Language is the corpus language as the Hub's metadata wants it.
const Language = "vi"

// Card renders the dataset card for a repo.
//
// A nil manifest is the repo before its first release: a working repo, which
// never gets one, and a published repo between being created and being filled.
// That card says so rather than printing zeros, because a card full of zeros
// reads as a snapshot that found nothing.
func Card(d Dataset, m *Manifest) string {
	var b strings.Builder
	cardFrontMatter(&b, d, m)
	cardBody(&b, d, m)
	return b.String()
}

// cardFrontMatter writes the YAML block the Hub reads. It is written by hand rather
// than marshaled because the Hub cares about the order of nothing in it and a
// person reading the file cares a great deal, and because a YAML dependency for
// twenty lines of output is a dependency to explain at every upgrade.
func cardFrontMatter(b *strings.Builder, d Dataset, m *Manifest) {
	b.WriteString("---\n")
	fmt.Fprintf(b, "pretty_name: %s\n", cardPretty(d.Name))
	b.WriteString("language:\n  - " + Language + "\n")

	// Not an SPDX identifier, because there is no single license here to name.
	// Every document carries its own class in the license_class column, and a
	// repo tagged cc-by-4.0 because most of it is would be telling a reader
	// something false about the rest.
	b.WriteString("license: other\n")
	fmt.Fprintf(b, "license_name: %s\n", cardLicenseName(d))
	fmt.Fprintf(b, "license_link: %s/blob/main/luat/posture.go\n", Repository)

	if m != nil {
		fmt.Fprintf(b, "size_categories:\n  - %s\n", cardSize(m.Counts.Documents))
	}
	if d.Text {
		b.WriteString("task_categories:\n  - text-generation\n  - fill-mask\n")
	}
	b.WriteString("tags:\n  - vietnamese\n")
	if !d.Text {
		b.WriteString("  - metadata-only\n")
	}
	if m != nil {
		b.WriteString("configs:\n  - config_name: default\n    data_files:\n")
		fmt.Fprintf(b, "      - split: train\n        path: %s/*%s\n", snapshotDir(m.Snapshot), ParquetExt)
	}
	b.WriteString("---\n\n")
}

func cardBody(b *strings.Builder, d Dataset, m *Manifest) {
	fmt.Fprintf(b, "# %s\n\n", cardPretty(d.Name))
	fmt.Fprintf(b, "This dataset is %s.\n\n", d.Holds)

	if m == nil {
		if d.Public() {
			b.WriteString("Nothing has been released to it yet. The card is regenerated from the manifest each time a snapshot is sealed, so when there is a snapshot this is where its counts will be.\n\n")
		}
	} else {
		cardSnapshot(b, m)
		cardCounts(b, m)
		cardStages(b, m)
	}
	cardShipping(b, d)
	cardReading(b, d, m)

	fmt.Fprintf(b, "## Where this comes from\n\n")
	fmt.Fprintf(b, "The pipeline that built it, the ingest contract every document had to pass, and the reasoning behind both are at %s.\n\n", Repository)
	fmt.Fprintf(b, "This card is generated by `gao kho card` from the snapshot manifest. Editing it by hand works until the next release overwrites it.\n")
}

func cardSnapshot(b *strings.Builder, m *Manifest) {
	b.WriteString("## This snapshot\n\n")
	b.WriteString("| | |\n| --- | --- |\n")
	fmt.Fprintf(b, "| snapshot | `%s` |\n", m.Snapshot)
	if m.Parent != "" {
		fmt.Fprintf(b, "| parent | `%s` |\n", m.Parent)
	}
	fmt.Fprintf(b, "| sealed | %s |\n", m.CreatedAt.UTC().Format("2006-01-02"))
	fmt.Fprintf(b, "| pipeline | %s |\n", m.Pipeline)
	if m.Box != "" {
		fmt.Fprintf(b, "| built on | %s |\n", m.Box)
	}
	fmt.Fprintf(b, "| files | %d |\n", len(m.Shards))
	fmt.Fprintf(b, "| merkle root | `%s` |\n", m.Root)
	fmt.Fprintf(b, "| signature | %s |\n", cardSigned(m))
	b.WriteString("\n")
	b.WriteString("The root commits to every file in the snapshot, and `gao kho verify` checks the files against it and the root against the signature. A snapshot is immutable: a document removed after this one was sealed is a tombstone in a later snapshot rather than an edit to this one.\n\n")
}

func cardSigned(m *Manifest) string {
	if m.Signature.Value == "" {
		return "unsigned, which means this is not a release"
	}
	return "`" + cardShort(m.Signature.PublicKey) + "` on " + m.Signature.SignedAt.UTC().Format("2006-01-02")
}

func cardCounts(b *strings.Builder, m *Manifest) {
	c := m.Counts
	b.WriteString("## What is in it\n\n")
	b.WriteString("| | |\n| --- | --- |\n")
	fmt.Fprintf(b, "| documents | %d |\n", c.Documents)
	if c.Synthetic > 0 {
		fmt.Fprintf(b, "| natural | %d |\n", c.Natural)
		fmt.Fprintf(b, "| synthetic | %d |\n", c.Synthetic)
	}
	fmt.Fprintf(b, "| characters | %d |\n", c.Chars)
	fmt.Fprintf(b, "| syllables | %d |\n", c.Syllables)
	if c.Tokens > 0 {
		fmt.Fprintf(b, "| tokens | %d, counted with %s |\n", c.Tokens, c.Tokenizer)
	}
	fmt.Fprintf(b, "| size | %s |\n", may.Size(c.Bytes))
	if c.Rejected > 0 {
		fmt.Fprintf(b, "| rejected while building | %d |\n", c.Rejected)
	}
	b.WriteString("\n")

	if c.Synthetic > 0 {
		b.WriteString("Synthetic documents are counted and reported and never added to the headline, which is the natural count.\n\n")
	}
	if len(c.BySource) > 0 {
		b.WriteString("| source | documents |\n| --- | --- |\n")
		for _, k := range cardSorted(c.BySource) {
			fmt.Fprintf(b, "| %s | %d |\n", k, c.BySource[k])
		}
		b.WriteString("\n")
	}
	if len(c.ByRejectReason) > 0 {
		b.WriteString("| dropped for | documents |\n| --- | --- |\n")
		for _, k := range cardSorted(c.ByRejectReason) {
			fmt.Fprintf(b, "| %s | %d |\n", k, c.ByRejectReason[k])
		}
		b.WriteString("\n")
	}
}

func cardStages(b *strings.Builder, m *Manifest) {
	if len(m.Stages) == 0 {
		return
	}
	b.WriteString("## How it was produced\n\n")
	b.WriteString("Run these stages in this order with these configurations and you get this snapshot back. The version in a stage name is part of the identity: two documents cleaned by different versions of the same stage are not comparable.\n\n")
	b.WriteString("| stage | config | from |\n| --- | --- | --- |\n")
	for _, s := range m.Stages {
		from := strings.Join(s.Inputs, ", ")
		if from == "" {
			from = "the sources in the ingest manifest"
		}
		fmt.Fprintf(b, "| %s | `%s` | %s |\n", s.Name, cardShort(s.ConfigHash.String()), from)
	}
	b.WriteString("\n")
}

func cardShipping(b *strings.Builder, d Dataset) {
	if !d.Public() {
		b.WriteString("## What this repo is\n\n")
		b.WriteString("Private working storage between passes, so that a worker can write a shard, push it and delete it rather than holding everything it has finished. Nothing here is published. What ships is decided by the published repo a document eventually lands in, and it is decided per document rather than per repo.\n\n")
		return
	}

	b.WriteString("## What ships and what does not\n\n")
	if d.Text {
		b.WriteString("This repo carries document text, so it carries only documents whose text may be redistributed.\n\n")
	} else {
		b.WriteString("This repo carries no document text. What it carries is the URL, the provenance columns and the scores, which is what lets somebody rebuild the same corpus from the same sources under their own lawful access.\n\n")
	}
	b.WriteString("| license class | text | metadata |\n| --- | --- | --- |\n")
	for _, c := range d.Classes {
		p := luat.Publishes(c)
		fmt.Fprintf(b, "| %s | %s | %s |\n", c, cardYes(p.Text && d.Text), cardYes(p.Metadata))
	}
	b.WriteString("\nEvery row carries its own class in the `license_class` column, so a reader who needs a narrower set than this repo holds can filter for it rather than trust the repo name.\n\n")
}

func cardReading(b *strings.Builder, d Dataset, m *Manifest) {
	b.WriteString("## Reading it\n\n")
	b.WriteString("The files are Parquet, partitioned by snapshot, so a query reads one column of one release rather than downloading the repo.\n\n")
	b.WriteString("```sql\n")
	if m == nil {
		fmt.Fprintf(b, "SELECT count(*) FROM read_parquet('hf://datasets/%s/%s/**/*%s');\n", d.Repo(), DataDir, ParquetExt)
	} else {
		fmt.Fprintf(b, "SELECT count(*) FROM %s;\n", d.Query(m.Snapshot))
	}
	b.WriteString("```\n\n")
}

// LicenseNamePattern is what the Hub requires a license_name to match. It is
// written down here because it is not free text, which is what it looks like
// until a commit comes back 400, and because the test that keeps the card
// loadable needs something to check against.
var LicenseNamePattern = regexp.MustCompile(`^[a-z0-9-.]+$`)

// cardLicenseName is the license_name field. It is a slug rather than a
// sentence, so the sentence it wants to be lives in the body: which classes a
// repo carries, and what happens to the text of each, are a table under what
// ships rather than a value the Hub will not accept.
func cardLicenseName(d Dataset) string {
	names := make([]string, 0, len(d.Classes))
	for _, c := range d.Classes {
		names = append(names, c.String())
	}
	return "per-document-" + strings.Join(names, "-")
}

// cardSize is the Hub's bucket for a document count. The buckets are theirs
// and the boundaries are inclusive at the bottom, which is why this walks a
// table rather than computing a power of ten: the top bucket has no upper bound
// and the bottom one has no lower bound, so the arithmetic has two special
// cases either way.
func cardSize(n int64) string {
	buckets := []struct {
		below int64
		name  string
	}{
		{1e3, "n<1K"},
		{1e4, "1K<n<10K"},
		{1e5, "10K<n<100K"},
		{1e6, "100K<n<1M"},
		{1e7, "1M<n<10M"},
		{1e8, "10M<n<100M"},
		{1e9, "100M<n<1B"},
		{1e10, "1B<n<10B"},
		{1e11, "10B<n<100B"},
		{1e12, "100B<n<1T"},
	}
	for _, b := range buckets {
		if n < b.below {
			return b.name
		}
	}
	return "n>1T"
}

// cardPretty turns a repo name into a title. The names are chosen to describe what
// is in them, which means they already read as titles once the hyphens are gone.
func cardPretty(name string) string {
	words := strings.Split(name, "-")
	for i, w := range words {
		if w == "urls" {
			words[i] = "URLs"
			continue
		}
		words[i] = strings.ToUpper(w[:1]) + w[1:]
	}
	return strings.Join(words, " ")
}

// cardShort cuts a hash to something a person can compare by eye. The full value is
// in the manifest, which is where anything mechanical reads it from.
func cardShort(h string) string {
	if len(h) <= 16 {
		return h
	}
	return h[:16]
}

func cardYes(b bool) string {
	if b {
		return "yes"
	}
	return "no"
}

// cardSorted orders a breakdown largest first, and by name where two are
// equal so the card does not change when nothing did.
func cardSorted(m map[string]int64) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool {
		if m[keys[i]] != m[keys[j]] {
			return m[keys[i]] > m[keys[j]]
		}
		return keys[i] < keys[j]
	})
	return keys
}
