package count_test

import (
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"testing"
	"unicode/utf8"

	"golang.org/x/text/unicode/norm"

	"github.com/tamnd/gao/count"
	"github.com/tamnd/gao/normalize"
)

// The inventory is the whole value of the chart, so it is checked against
// somebody else's list of the letters rather than against our own count of them.
//
// normalize keeps what iconv encodes each of the 134 letters of Vietnamese as,
// one to a line, generated by asking iconv and committed so that it runs on a
// machine with no iconv on it. That file was written for a different purpose,
// which is what makes it worth reading here: it is an inventory of the
// language that nothing in this package had a hand in.
func TestTheChartCarriesEveryLetterIconvKnowsAbout(t *testing.T) {
	letters := iconvLetters(t, filepath.Join("..", "normalize", "testdata", "legacy", "viscii.iconv"))
	if len(letters) != 134 {
		t.Fatalf("the list names %d letters and Vietnamese has 134", len(letters))
	}

	chart := count.Letters()
	if len(chart) != 134 {
		t.Errorf("the chart carries %d letters and Vietnamese has 134", len(chart))
	}
	for _, r := range letters {
		if !slices.Contains(chart, r) {
			t.Errorf("the chart is missing %q", string(r))
		}
	}
	for _, r := range chart {
		if !slices.Contains(letters, r) {
			t.Errorf("the chart carries %q, which is not a letter of Vietnamese", string(r))
		}
	}
}

// iconvLetters reads the letters out of normalize's iconv file, which is a
// letter, a space, and the bytes in hex.
func iconvLetters(t *testing.T, path string) []rune {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	var out []rune
	for line := range strings.Lines(string(data)) {
		field, _, ok := strings.Cut(strings.TrimSpace(line), " ")
		if !ok {
			continue
		}
		r, size := utf8.DecodeRuneInString(field)
		if size != len(field) {
			t.Fatalf("%q is not one letter", field)
		}
		out = append(out, r)
	}
	return out
}

// The legacy documents are copies, and a copy that drifts from what it was
// copied from is worse than no copy at all, since it looks like the same fixture
// and is not.
func TestTheLegacySamplesAreTheOnesNormalizeWasTestedAgainst(t *testing.T) {
	golden := map[string]string{
		"song-hong":     "song-hong.tcvn3.txt",
		"pho-co-ha-noi": "pho-co-ha-noi.tcvn3.txt",
		"cong-bao":      "cong-bao.viscii.txt",
	}
	for _, c := range count.Coverage() {
		name, ok := golden[c.Name]
		if !ok {
			continue
		}
		want, err := os.ReadFile(filepath.Join("..", "normalize", "testdata", "legacy", name))
		if err != nil {
			t.Fatal(err)
		}
		if c.Text != string(want) {
			t.Errorf("%s has drifted from normalize/testdata/legacy/%s", c.Name, name)
		}
	}
}

// One sample per encoding, which is the point of having the legacy documents
// in the set at all. Where two encodings carry the same text after transcoding
// they share a sample, and that they do is what normalize's golden set proves.
func TestEveryEncodingNormalizeReadsHasASampleInTheSet(t *testing.T) {
	covered := map[string]bool{}
	for _, c := range count.Coverage() {
		for _, name := range c.Charsets {
			covered[name] = true
		}
	}
	for _, c := range normalize.Charsets() {
		if !covered[c.Name()] {
			t.Errorf("no document in the coverage set comes out of %s", c.Name())
		}
	}
}

// The set exists so that a gate cannot quietly not run, so that is what is
// asserted about it. A faithful tokenizer over this text leaves nothing unrun
// and nothing failing.
//
// T9 is the exception and is checked by the test below instead. It is a
// measurement of the machine, and four kilobytes go through a tokenizer faster
// than the clock can be read.
func TestTheCoverageSetLeavesNoGateUnrun(t *testing.T) {
	g := count.NewGates(faithful(), count.GateOptions{})
	for _, c := range count.Coverage() {
		if !g.Add(c.ID(), c.Text) {
			t.Errorf("%s was not part of the sample", c.Name)
		}
	}
	report := g.Report()

	for _, gate := range report.Gates {
		switch {
		case gate.Audit, gate.Name == count.ThroughputGate:
			continue
		case !gate.Ran:
			t.Errorf("%s did not run on the coverage set: %s", gate.Name, gate.Why)
		case gate.Failed > 0:
			t.Errorf("%s failed %d of %d %s on a faithful tokenizer: %v", gate.Name, gate.Failed, gate.Checked, gate.Unit, gate.Sample)
		}
	}
	if !report.Correct() {
		t.Error("a tokenizer that breaks no rule fails a correctness gate on the coverage set")
	}
}

// The throughput gate declines on a sample this small rather than reporting the
// rate it computed, because that rate is a reading of the clock. A suite that
// called four kilobytes 17 MB/s would be handing somebody a number they could
// not defend, and one that called it a pass would be worse.
//
// What it declines on is the size of the sample and not the time the sample
// took, so this test says the same thing on a box whose clock is fine and on a
// box whose clock ticks every 15.6 milliseconds and reports one whole tick for
// the whole set.
func TestTheSetIsTooSmallToTimeAndSaysSo(t *testing.T) {
	report := feedCoverage(t)

	g := gate(t, report, count.ThroughputGate)
	if g.Ran {
		t.Fatalf("T9 reported a rate on a %d byte sample: %s", report.Chars, g.Note)
	}
	if !strings.Contains(g.Why, "reading of the clock") {
		t.Errorf("T9 declined and said %q, which does not say why the number would be meaningless", g.Why)
	}
	if report.Eligible() {
		t.Error("the coverage set decided eligibility, and it is four kilobytes of letter chart")
	}
}

// T6 is the gate the set was hardest to write for. A corpus of clean web text
// is NFC throughout, so the gate compares every document against itself and
// reports a pass it did not earn. The decomposed chart is what stops that.
func TestTheSetHoldsTextThatIsNotAlreadyNormalized(t *testing.T) {
	var decomposed int
	for _, c := range count.Coverage() {
		if norm.NFC.String(c.Text) != c.Text {
			decomposed++
		}
	}
	if decomposed == 0 {
		t.Fatal("every document in the set is already NFC, so T6 compares each one against itself")
	}

	report := feedCoverage(t)
	note := gate(t, report, "T6").Note
	if strings.Contains(note, "against itself") {
		t.Errorf("T6 says %q, and the set is supposed to give it something to do", note)
	}
	if !strings.HasPrefix(note, strconv.Itoa(decomposed)+" of ") {
		t.Errorf("T6 says %q, and %d documents in the set are not NFC", note, decomposed)
	}
}

// T3 is the other one. It is the gate a real sample most often leaves unrun,
// because a document has to hold Vietnamese, English and code at once before it
// has anything to say.
func TestTheSetHoldsTheDocumentT3NeedsAndTheOneT7Needs(t *testing.T) {
	report := feedCoverage(t)

	if g := gate(t, report, "T3"); !g.Ran {
		t.Errorf("T3 did not run: %s", g.Why)
	} else if g.Checked == 0 {
		t.Error("T3 ran and checked nothing")
	}
	if g := gate(t, report, "T7"); g.Checked < 4 {
		t.Errorf("T7 checked %d digit runs, and it cannot tell grouping from context on fewer", g.Checked)
	}
	if g := gate(t, report, "T8"); g.Checked < 100 {
		t.Errorf("T8 checked %d syllables, and the chart alone should give it more", g.Checked)
	}
}

// Every document in the set says what it is for. A coverage set without that
// grows documents nobody can remove, because nobody can tell what removing one
// would stop covering.
func TestEveryDocumentSaysWhatItIsForAndIsDistinct(t *testing.T) {
	seen := map[string]bool{}
	for _, c := range count.Coverage() {
		switch {
		case c.Name == "":
			t.Error("a document in the set has no name")
		case len(c.Why) < 40:
			t.Errorf("%s says %q, which is not a reason", c.Name, c.Why)
		case strings.TrimSpace(c.Text) == "":
			t.Errorf("%s is empty", c.Name)
		}
		if seen[c.ID().String()] {
			t.Errorf("%s is the same text as an earlier document", c.Name)
		}
		seen[c.ID().String()] = true
	}
}

// The set is fixed, and being fixed is what lets the same run on four boxes be
// compared as four numbers rather than as four reports.
func TestTheSetIsTheSameEveryTime(t *testing.T) {
	first, second := count.Coverage(), count.Coverage()
	if len(first) != len(second) {
		t.Fatalf("the set is %d documents and then %d", len(first), len(second))
	}
	for i := range first {
		if first[i].Name != second[i].Name || first[i].Text != second[i].Text {
			t.Errorf("document %d changed between two calls", i)
		}
	}
}

func feedCoverage(t *testing.T) count.GateReport {
	t.Helper()
	g := count.NewGates(faithful(), count.GateOptions{})
	for _, c := range count.Coverage() {
		g.Add(c.ID(), c.Text)
	}
	return g.Report()
}

// faithful is a tokenizer that breaks none of the rules: it splits characters
// rather than bytes, it keeps a character whole, and it normalizes what it is
// given, which is what makes it stable across the two ways of writing a mark.
func faithful() count.Encoder {
	t := newToy("faithful", byRune, " ")
	t.nfc = true
	return t
}
